// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_ScrMulti_screen_init(void)
{
    ui_ScrMulti = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrMulti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrMulti, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMultiName = lv_label_create(ui_ScrMulti);
    lv_obj_set_width(ui_LblMultiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMultiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMultiName, 2);
    lv_obj_set_y(ui_LblMultiName, 94);
    lv_obj_set_align(ui_LblMultiName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMultiName, "Screen");
    lv_obj_set_style_text_color(ui_LblMultiName, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMultiName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMultiName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_PnlMulti0, -43);
    lv_obj_set_y(ui_PnlMulti0, -40);



    lv_obj_set_x(ui_PnlMulti1, 43);
    lv_obj_set_y(ui_PnlMulti1, -40);



    lv_obj_set_x(ui_PnlMulti2, -43);
    lv_obj_set_y(ui_PnlMulti2, 40);



    lv_obj_set_x(ui_PnlMulti3, 43);
    lv_obj_set_y(ui_PnlMulti3, 40);



    ui_ImgButtonSwitchSmall1 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_ImgButtonSwitchSmall1, -47);
    lv_obj_set_y(ui_ImgButtonSwitchSmall1, 8);
    lv_obj_clear_flag(ui_ImgButtonSwitchSmall1, LV_OBJ_FLAG_HIDDEN);      /// Flags


    ui_ImgButtonSwitchSmall3 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_ImgButtonSwitchSmall3, -50);
    lv_obj_set_y(ui_ImgButtonSwitchSmall3, 40);
    lv_obj_add_flag(ui_ImgButtonSwitchSmall3, LV_OBJ_FLAG_HIDDEN);     /// Flags


    ui_ImgButtonSwitchSmall2 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_ImgButtonSwitchSmall2, 50);
    lv_obj_set_y(ui_ImgButtonSwitchSmall2, -50);
    lv_obj_add_flag(ui_ImgButtonSwitchSmall2, LV_OBJ_FLAG_HIDDEN);     /// Flags


    ui_ImgButtonSwitchSmall4 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_ImgButtonSwitchSmall4, 50);
    lv_obj_set_y(ui_ImgButtonSwitchSmall4, 40);
    lv_obj_add_flag(ui_ImgButtonSwitchSmall4, LV_OBJ_FLAG_HIDDEN);     /// Flags


    lv_obj_add_event_cb(ui_PnlMulti0, ui_event_ ?, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PnlMulti1, ui_event_ ?, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PnlMulti2, ui_event_ ?, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PnlMulti3, ui_event_ ?, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMulti, ui_event_ScrMulti, LV_EVENT_ALL, NULL);

}
