// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#ifndef _UI_COMP_BTNSENSSMALL_H
#define _UI_COMP_BTNSENSSMALL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BtnSensSmall
#define UI_COMP_BTNSENSSMALL_BTNSENSSMALL 0
#define UI_COMP_BTNSENSSMALL_LBLSENSSMALLPEER 1
#define UI_COMP_BTNSENSSMALL_LBLSENSSMALLPERIPH 2
#define UI_COMP_BTNSENSSMALL_LBLSENSSMALLVALUE 3
#define UI_COMP_BTNSENSSMALL_ARC2 4
#define _UI_COMP_BTNSENSSMALL_NUM 5
lv_obj_t * ui_BtnSensSmall_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
