// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"


// COMPONENT PnlMulti

lv_obj_t * ui_PnlMulti_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_PnlMulti;
    cui_PnlMulti = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_PnlMulti, 86);
    lv_obj_set_height(cui_PnlMulti, 80);
    lv_obj_set_x(cui_PnlMulti, -45);
    lv_obj_set_y(cui_PnlMulti, -40);
    lv_obj_set_align(cui_PnlMulti, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PnlMulti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PnlMulti, lv_color_hex(0x135A25), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PnlMulti, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblMultiPeriph;
    cui_LblMultiPeriph = lv_label_create(cui_PnlMulti);
    lv_obj_set_width(cui_LblMultiPeriph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblMultiPeriph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblMultiPeriph, 0);
    lv_obj_set_y(cui_LblMultiPeriph, -25);
    lv_obj_set_align(cui_LblMultiPeriph, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblMultiPeriph, "Periph");
    lv_obj_set_style_text_color(cui_LblMultiPeriph, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LblMultiPeriph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblMultiPeer;
    cui_LblMultiPeer = lv_label_create(cui_PnlMulti);
    lv_obj_set_width(cui_LblMultiPeer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblMultiPeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblMultiPeer, 0);
    lv_obj_set_y(cui_LblMultiPeer, 25);
    lv_obj_set_align(cui_LblMultiPeer, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblMultiPeer, "Peer");
    lv_obj_set_style_text_color(cui_LblMultiPeer, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LblMultiPeer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LblMultiPeer, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblMultiValue;
    cui_LblMultiValue = lv_label_create(cui_PnlMulti);
    lv_obj_set_width(cui_LblMultiValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblMultiValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblMultiValue, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblMultiValue, "---");
    lv_obj_set_style_text_color(cui_LblMultiValue, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LblMultiValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LblMultiValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_LblMultiValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_LblMultiValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_LblMultiValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_LblMultiValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PNLMULTI_NUM);
    children[UI_COMP_PNLMULTI_PNLMULTI] = cui_PnlMulti;
    children[UI_COMP_PNLMULTI_LBLMULTIPERIPH] = cui_LblMultiPeriph;
    children[UI_COMP_PNLMULTI_LBLMULTIPEER] = cui_LblMultiPeer;
    children[UI_COMP_PNLMULTI_LBLMULTIVALUE] = cui_LblMultiValue;
    lv_obj_add_event_cb(cui_PnlMulti, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_PnlMulti, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_PnlMulti_create_hook(cui_PnlMulti);
    return cui_PnlMulti;
}

