// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#ifndef _UI_COMP_IMGBUTTONSWITCHSMALL_H
#define _UI_COMP_IMGBUTTONSWITCHSMALL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ImgButtonSwitchSmall
#define UI_COMP_IMGBUTTONSWITCHSMALL_IMGBUTTONSWITCHSMALL 0
#define UI_COMP_IMGBUTTONSWITCHSMALL_LBLPEER 1
#define UI_COMP_IMGBUTTONSWITCHSMALL_LBLPERIPH 2
#define _UI_COMP_IMGBUTTONSWITCHSMALL_NUM 3
lv_obj_t * ui_ImgButtonSwitchSmall_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
