// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#ifndef _UI_COMP_PNLMULTI_H
#define _UI_COMP_PNLMULTI_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PnlMulti
#define UI_COMP_PNLMULTI_PNLMULTI 0
#define UI_COMP_PNLMULTI_LBLMULTIPERIPH 1
#define UI_COMP_PNLMULTI_LBLMULTIPEER 2
#define UI_COMP_PNLMULTI_LBLMULTIVALUE 3
#define _UI_COMP_PNLMULTI_NUM 4
lv_obj_t * ui_PnlMulti_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
