// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"


// COMPONENT BtnSensSmall

lv_obj_t * ui_BtnSensSmall_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BtnSensSmall;
    cui_BtnSensSmall = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_BtnSensSmall, 90);
    lv_obj_set_height(cui_BtnSensSmall, 90);
    lv_obj_set_x(cui_BtnSensSmall, -42);
    lv_obj_set_y(cui_BtnSensSmall, -48);
    lv_obj_set_align(cui_BtnSensSmall, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_BtnSensSmall, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_BtnSensSmall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_BtnSensSmall, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_BtnSensSmall, lv_color_hex(0x165420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BtnSensSmall, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_BtnSensSmall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_BtnSensSmall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_BtnSensSmall, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_BtnSensSmall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_BtnSensSmall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(cui_BtnSensSmall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(cui_BtnSensSmall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblSensSmallPeer;
    cui_LblSensSmallPeer = lv_label_create(cui_BtnSensSmall);
    lv_obj_set_width(cui_LblSensSmallPeer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblSensSmallPeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblSensSmallPeer, 0);
    lv_obj_set_y(cui_LblSensSmallPeer, 25);
    lv_obj_set_align(cui_LblSensSmallPeer, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblSensSmallPeer, "Peer");
    lv_obj_set_style_text_font(cui_LblSensSmallPeer, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblSensSmallPeriph;
    cui_LblSensSmallPeriph = lv_label_create(cui_BtnSensSmall);
    lv_obj_set_width(cui_LblSensSmallPeriph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblSensSmallPeriph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LblSensSmallPeriph, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblSensSmallPeriph, "Periph");

    lv_obj_t * cui_LblSensSmallValue;
    cui_LblSensSmallValue = lv_label_create(cui_BtnSensSmall);
    lv_obj_set_width(cui_LblSensSmallValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblSensSmallValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblSensSmallValue, 0);
    lv_obj_set_y(cui_LblSensSmallValue, -25);
    lv_obj_set_align(cui_LblSensSmallValue, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblSensSmallValue, "value");

    lv_obj_t * cui_Arc2;
    cui_Arc2 = lv_arc_create(cui_BtnSensSmall);
    lv_obj_set_width(cui_Arc2, 90);
    lv_obj_set_height(cui_Arc2, 90);
    lv_obj_set_align(cui_Arc2, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_color(cui_Arc2, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_Arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_Arc2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(cui_Arc2, lv_color_hex(0x398F30), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_Arc2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_Arc2, lv_color_hex(0xDBDBDB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Arc2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTNSENSSMALL_NUM);
    children[UI_COMP_BTNSENSSMALL_BTNSENSSMALL] = cui_BtnSensSmall;
    children[UI_COMP_BTNSENSSMALL_LBLSENSSMALLPEER] = cui_LblSensSmallPeer;
    children[UI_COMP_BTNSENSSMALL_LBLSENSSMALLPERIPH] = cui_LblSensSmallPeriph;
    children[UI_COMP_BTNSENSSMALL_LBLSENSSMALLVALUE] = cui_LblSensSmallValue;
    children[UI_COMP_BTNSENSSMALL_ARC2] = cui_Arc2;
    lv_obj_add_event_cb(cui_BtnSensSmall, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BtnSensSmall, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BtnSensSmall_create_hook(cui_BtnSensSmall);
    return cui_BtnSensSmall;
}

