// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_ScrMulti_screen_init(void)
{
    ui_ScrMulti = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrMulti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrMulti, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSwitchSmall1 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSwitchSmall1, -43);
    lv_obj_set_y(ui_BtnSwitchSmall1, -49);
    lv_obj_clear_flag(ui_BtnSwitchSmall1, LV_OBJ_FLAG_HIDDEN);      /// Flags


    ui_BtnSwitchSmall2 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSwitchSmall2, 50);
    lv_obj_set_y(ui_BtnSwitchSmall2, -49);
    lv_obj_clear_flag(ui_BtnSwitchSmall2, LV_OBJ_FLAG_HIDDEN);      /// Flags


    ui_BtnSwitchSmall3 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSwitchSmall3, -43);
    lv_obj_set_y(ui_BtnSwitchSmall3, 43);
    lv_obj_clear_flag(ui_BtnSwitchSmall3, LV_OBJ_FLAG_HIDDEN);      /// Flags


    ui_BtnSwitchSmall4 = ui_ButtonSwitchSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSwitchSmall4, 50);
    lv_obj_set_y(ui_BtnSwitchSmall4, 43);
    lv_obj_clear_flag(ui_BtnSwitchSmall4, LV_OBJ_FLAG_HIDDEN);      /// Flags


    ui_BtnSensSmall1 = ui_BtnSensSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSensSmall1, -42);
    lv_obj_set_y(ui_BtnSensSmall1, -48);
    lv_obj_clear_flag(ui_BtnSensSmall1, LV_OBJ_FLAG_HIDDEN);      /// Flags





    ui_BtnSensSmall2 = ui_BtnSensSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSensSmall2, 50);
    lv_obj_set_y(ui_BtnSensSmall2, -50);
    lv_obj_clear_flag(ui_BtnSensSmall2, LV_OBJ_FLAG_HIDDEN);      /// Flags





    ui_BtnSensSmall3 = ui_BtnSensSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSensSmall3, -43);
    lv_obj_set_y(ui_BtnSensSmall3, 45);
    lv_obj_clear_flag(ui_BtnSensSmall3, LV_OBJ_FLAG_HIDDEN);      /// Flags





    ui_BtnSensSmall4 = ui_BtnSensSmall_create(ui_ScrMulti);
    lv_obj_set_x(ui_BtnSensSmall4, 50);
    lv_obj_set_y(ui_BtnSensSmall4, 45);
    lv_obj_clear_flag(ui_BtnSensSmall4, LV_OBJ_FLAG_HIDDEN);      /// Flags





    ui_LblMultiName = lv_label_create(ui_ScrMulti);
    lv_obj_set_width(ui_LblMultiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMultiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMultiName, 2);
    lv_obj_set_y(ui_LblMultiName, 94);
    lv_obj_set_align(ui_LblMultiName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMultiName, "Screen");
    lv_obj_set_style_text_color(ui_LblMultiName, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMultiName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMultiName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrMulti, ui_event_ScrMulti, LV_EVENT_ALL, NULL);

}
