// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_ScreenEichen_screen_init(void)
{
    ui_ScreenEichen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEichen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenEichen, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);


}
