// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_ScrSingle_screen_init(void)
{
    ui_ScrSingle = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSingle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrSingle, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSingle1 = lv_label_create(ui_ScrSingle);
    lv_obj_set_width(ui_LblSingle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSingle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblSingle1, 0);
    lv_obj_set_y(ui_LblSingle1, 90);
    lv_obj_set_align(ui_LblSingle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSingle1, "Peer");
    lv_obj_set_style_text_color(ui_LblSingle1, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSingle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSingle1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrSingle, ui_event_ScrSingle, LV_EVENT_ALL, NULL);

}
