// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Jeepify

#include "../ui.h"

void ui_ScreenVolt_screen_init(void)
{
    ui_ScreenVolt = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenVolt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenVolt, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_ScreenVolt);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 180);
    lv_obj_set_height(ui_Keyboard2, 141);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);


}
